(Fix) Updated the procedures and imaging apps to load the current day orders by default on page load
palladiumkenya/kenyaemr-esm-orders pull request #10
Opened 2024-12-02 09:21 UTC by FelixKiprotich350

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Updated the procedures and imaging apps to load the current day orders by default on page load. You can later adjsut the dates as you want. This helps in avoiding loading and unnecessary orders and improves efficiency

## Screenshots

![Screenshot from 2024-12-02 12-21-25](https://github.com/user-attachments/assets/39634a6c-ff06-4a47-93da-4745f17a4e67)

## Related Issue

*None.*

## Other

*None.*

2024-12-02 20:04 UTC, ojwanganto commented
Thanks, kongozi. We would like to have the same apply to all the tabs so that we consistently have efficiency across the tabs. I think the implementation in the lab module already has this. Please check if there is anything already that we can borrow.

2024-12-02 20:45 UTC, makombe commented on packages/esm-imaging-orders-app/src/shared/ui/common/grouped-orders-table.component.tsx
> +                  placeholder={t('searchbypatientname', 'Search by patient name')}
```suggestion
                  placeholder={t('searchByPatientName', 'Search by patient name')}
```

2024-12-02 20:47 UTC, makombe commented on packages/esm-procedure-orders-app/src/shared/ui/common/grouped-orders-table.component.tsx
> +                  placeholder={t('searchbypatientname', 'Search by patient name')}
```suggestion
                  placeholder={t('searchByPatientName', 'Search by patient name')}
```

2024-12-02 20:48 UTC, makombe commented on packages/esm-procedure-orders-app/src/shared/ui/common/grouped-orders-table.scss
> +    height: spacing.$spacing-09;
```suggestion
    height: layout.$spacing-09;
```

2024-12-02 20:48 UTC, makombe commented on packages/esm-procedure-orders-app/src/shared/ui/common/grouped-orders-table.scss
> +    height: spacing.$spacing-09;
```suggestion
    height: layout.$spacing-09;
```

2024-12-05 09:21 UTC, FelixKiprotich350 commented
> same

Noted ill work on this.

2024-12-05 11:23 UTC, donaldkibet requested changes
Thanks @FelixKiprotich350, Great work. I final request could we have unit test to try prevent regression

2024-12-05 11:23 UTC, donaldkibet commented on packages/esm-imaging-orders-app/src/hooks/useOrdersWorklist.ts
> +  radiologyOrderTypeUuid: string,
```suggestion
  orderTypeUuid: string,
```

2024-12-05 11:23 UTC, donaldkibet commented on packages/esm-imaging-orders-app/src/hooks/useOrdersWorklist.ts
> +    [radiologyOrderTypeUuid, dateRange.at(0).toISOString(), dateRange.at(1).toISOString(), fulfillerStatus],
Check this linting errors and fix them

2024-12-10 03:48 UTC, donaldkibet approved these changes

2024-12-10 03:48 UTC, merged