(feat): updated the functionality of the imaging order
palladiumkenya/kenyaemr-esm-orders pull request #12
Opened 2024-12-16 12:53 UTC by its-kios09

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
- Add Age,  Gender and clinical diagnosis as part of  the patient info on the imaging panel
- Review of the imaging procedure before approval
- Printing of the results
- Updated the UI

## Screenshots

*None.*

## Related Issue

*None.*

## Other

*None.*

2024-12-16 18:38 UTC, ojwanganto commented
Thanks so much, @its-kios09. I am wondering whether we can make the report body showing the report and other details a bit bigger and centralized?

2024-12-16 19:01 UTC, its-kios09 commented
> Thanks so much, @its-kios09. I am wondering whether we can make the report body showing the report and other details a bit bigger and centralized? I just googled and got the below sample. Do you think we can achieve something similar or close?
> 
> ![image](https://private-user-images.githubusercontent.com/2161877/396228678-313703a6-6392-4fce-851d-15ee9828c9ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNzU5MDcsIm5iZiI6MTczNDM3NTYwNywicGF0aCI6Ii8yMTYxODc3LzM5NjIyODY3OC0zMTM3MDNhNi02MzkyLTRmY2UtODUxZC0xNWVlOTgyOGM5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMTkwMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmZiY2UwYmU3MzQ2NTVhZjgyNGE4MjM1NDc3ZTU0MDA5ZmYwM2I5YTg0ZTBiYTE3ZWIyY2MyNDkyZDZlMmNiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SK2zM5fUuZeEk_8e3jFRLpBT4nKqHa-iAz3N0SOOfWc)

Yes, let me design the report then i will share it with you

2024-12-17 07:27 UTC, donaldkibet requested changes
[Kapture 2024-12-17 at 10.25.29.webm](https://github.com/user-attachments/assets/bda200c8-936d-4913-a1da-d9b2750f4fcd)

Am getting this error on running this PR

2024-12-17 07:27 UTC, donaldkibet commented on packages/esm-imaging-orders-app/src/form/review-form/review-imaging-form.scss
> +  --cds-layout-size-height: var(--cds-layout-size-height-context);
why use this and we have the tokens for length e.g `layout.$spacing-05`

2024-12-17 07:27 UTC, donaldkibet commented on packages/esm-imaging-orders-app/src/form/review-form/review-imaging-form.scss
> +  }
Is this working well on tablets

2024-12-17 08:53 UTC, donaldkibet commented
cc @its-kios09 see the conflicts

2024-12-17 10:56 UTC, its-kios09 commented on packages/esm-imaging-orders-app/src/form/review-form/review-imaging-form.scss
> +  }
Addressed

2024-12-17 10:57 UTC, its-kios09 commented on packages/esm-imaging-orders-app/src/form/review-form/review-imaging-form.scss
> +  --cds-layout-size-height: var(--cds-layout-size-height-context);
sorted

2024-12-17 13:23 UTC, donaldkibet approved these changes

2024-12-17 20:11 UTC, ojwanganto commented
Do we really need the background colors for order status and no instructions? Could we just adopt a UI that's not very shouting? Disclaimer: Am not a UI expert :)
We can discuss this for the next iteration

2024-12-17 21:16 UTC, donaldkibet commented
Sure @ojwanganto, Merging this in

2024-12-17 21:16 UTC, merged